# Generated by Django 4.1.3 on 2022-11-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comentario_comuna_familiar_ficha_funcionario_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
    ]
