# Generated by Django 4.1.3 on 2022-11-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_paciente_contrasenia_remove_paciente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='id_paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.paciente'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.paciente'),
        ),
    ]
