# Generated by Django 4.1.3 on 2022-11-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_familiar_id_paciente_alter_ficha_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.paciente'),
        ),
    ]
