# Generated by Django 4.1.3 on 2022-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_familiar_id_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_region',
        ),
        migrations.AddField(
            model_name='familiar',
            name='id_comuna',
            field=models.ManyToManyField(to='main_app.comuna'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='id_region',
            field=models.ManyToManyField(to='main_app.region'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_comuna',
            field=models.ManyToManyField(to='main_app.comuna'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_region',
            field=models.ManyToManyField(to='main_app.region'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_comuna',
            field=models.ManyToManyField(to='main_app.comuna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_region',
            field=models.ManyToManyField(to='main_app.region'),
        ),
    ]
