# Generated by Django 4.1.3 on 2022-11-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_familiar_id_comuna_remove_familiar_id_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.paciente'),
        ),
    ]
