# Generated by Django 4.1.3 on 2022-11-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_familiar_id_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='id_comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.comentario'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ingreso'),
        ),
    ]
